# Generated by Django 4.2 on 2023-04-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicles',
            fields=[
                ('Title', models.CharField(max_length=255)),
                ('Sub_title', models.CharField(max_length=255)),
                ('Price', models.CharField(max_length=255)),
                ('Brand', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('Edition', models.CharField(max_length=255)),
                ('Year', models.CharField(max_length=255)),
                ('Condition', models.CharField(max_length=255)),
                ('Transmission', models.CharField(max_length=255)),
                ('Body', models.CharField(max_length=255)),
                ('Fuel', models.CharField(max_length=255)),
                ('Capacity', models.CharField(max_length=255)),
                ('Mileage', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Post_url', models.CharField(max_length=255)),
                ('Seller_name', models.CharField(max_length=255)),
                ('Seller_type', models.CharField(max_length=255)),
                ('Published_date', models.CharField(max_length=255)),
                ('Vehicle_Id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='Vehicle_Id'
                )),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='user_vehicle',
            fields=[
                ('Client_Id', models.BigIntegerField()),
                ('Vehicle_Id', models.BigIntegerField()),
                ('uv_Id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='Vehicle_Id'
                )),
            ],
            options={
                'db_table': 'user_vehicle',
            },
        ),
    ]
