# Generated by Django 4.2 on 2023-04-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVehicle',
            fields=[
                ('uv_Id', models.BigIntegerField(db_column='uv_Id', primary_key=True, serialize=False)),
                ('Vehicle_Id', models.BigIntegerField()),
                ('Client_Id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'user_vehicle',
            },
        ),
        migrations.DeleteModel(
            name='user_vehicle',
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='body',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='capacity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='condition',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='edition',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='fuel',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='mileage',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='post_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='published_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='seller_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='seller_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='sub_title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='transmission',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_Id',
            field=models.BigIntegerField(db_column='Vehicle_Id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
