# Generated by Django 4.2 on 2023-04-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_vehicles_body_alter_vehicles_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='Brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Condition',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Post_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Sub_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Transmission',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Vehicle_Id',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Year',
            field=models.IntegerField(max_length=4),
        ),
    ]
