# Generated by Django 4.2 on 2023-05-02 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uservehicle_delete_user_vehicle_alter_vehicles_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservehicle',
            old_name='Client_Id',
            new_name='Client_id',
        ),
        migrations.AlterField(
            model_name='uservehicle',
            name='Vehicle_Id',
            field=models.ForeignKey(db_column='Vehicle_Id', on_delete=django.db.models.deletion.CASCADE, to='app.vehicles'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_Id',
            field=models.BigIntegerField(db_column='vehicle_Id', primary_key=True, serialize=False),
        ),
    ]
