# Generated by Django 4.2 on 2023-04-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_vehicles_brand_alter_vehicles_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='Year',
            field=models.CharField(max_length=4),
        ),
    ]
