# Generated by Django 4.2 on 2023-04-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_vehicles_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='Vehicle_Id',
            field=models.IntegerField(),
        ),
    ]
