# Generated by Django 4.2 on 2023-04-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_vehicles_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='Description',
            field=models.TextField(),
        ),
    ]
