# Generated by Django 4.2 on 2023-04-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_vehicles_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='Edition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Published_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Seller_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Seller_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Sub_title',
            field=models.TextField(),
        ),
    ]
