# Generated by Django 4.2 on 2023-04-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_vehicles_edition_alter_vehicles_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='Edition',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='Mileage',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='Seller_name',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='Seller_type',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='Sub_title',
        ),
    ]
