# Generated by Django 4.2 on 2023-04-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_vehicles_description_remove_vehicles_edition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='Post_url',
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Body',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Brand',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Capacity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Condition',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Fuel',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Model',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Transmission',
            field=models.CharField(max_length=200),
        ),
    ]
