# Generated by Django 4.2 on 2023-04-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_vehicles_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uv_Id', models.BigIntegerField()),
                ('Vehicle_Id', models.BigIntegerField()),
                ('Client_Id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'user_vehicle',
            },
        ),
        migrations.AddField(
            model_name='vehicles',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='Edition',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='Mileage',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='Post_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='Seller_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='Seller_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='Sub_title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Body',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Capacity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Condition',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Fuel',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Published_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Transmission',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Vehicle_Id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
