# Generated by Django 4.2 on 2023-04-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_uservehicle_vehicles_description_vehicles_edition_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_vehicle',
        ),
    ]
