# Generated by Django 4.2 on 2023-04-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_user_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservehicle',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='id',
        ),
        migrations.AlterField(
            model_name='uservehicle',
            name='uv_Id',
            field=models.BigIntegerField(db_column='uv_Id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Vehicle_Id',
            field=models.BigIntegerField(db_column='Vehicle_Id', primary_key=True, serialize=False),
        ),
    ]
