# Generated by Django 4.2 on 2023-04-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_uservehicle_id_remove_vehicles_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Vehicle_Id',
            field=models.BigIntegerField(),
        ),
    ]
