# Generated by Django 4.2 on 2023-04-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_vehicles_id_alter_vehicles_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uservehicle',
            name='uv_Id',
            field=models.BigIntegerField(),
        ),
    ]
