# Generated by Django 4.2 on 2023-04-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_uservehicle_id_alter_uservehicle_uv_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservehicle',
            name='id',
        ),
        migrations.AlterField(
            model_name='uservehicle',
            name='uv_Id',
            field=models.BigIntegerField(db_column='uv_Id', primary_key=True, serialize=False),
        ),
    ]
